### ISSUE TITLE
No checkpoint made

### ISSUE THREAD

**Issue by matigekunstintelligentie** [archinetai/audio-diffusion-pytorch-trainer#2]
I ran the instructions and only removed the wandb loggers from the yaml and module_base. No checkpoint is being made in the log directory. It logs: - Best model ckpt at 
And no path

**Comment by flavioschneider** [comment]
The checkpoint is created at the end of the epoch. If you run the model for less than an epoch, the "model ckpt at" returns an empty string since there's no checkpoint yet.

**Comment by matigekunstintelligentie** [comment]
This is after epochs have completed

**Comment by flavioschneider** [comment]
Mhh, this is weird. Could you provide the `.yaml` file you're using?

**Comment by matigekunstintelligentie** [comment]
```
# @package _global_

# Test with length 65536, batch size 4, logger sampling_steps [3]

sampling_rate: 48000
length: 65536
channels: 2
log_every_n_steps: 2000

model:
  _target_: main.module_base.Model
  learning_rate: 1e-4
  beta1: 0.9
  beta2: 0.99
  in_channels: ${channels}
  channels: 128
  patch_size: 16
  resnet_groups: 8
  kernel_multiplier_downsample: 2
  kernel_sizes_init: [1, 3, 7]
  multipliers: [1, 2, 4, 4, 4, 4, 4]
  factors: [4, 4, 4, 2, 2, 2]
  num_blocks: [2, 2, 2, 2, 2, 2]
  attentions: [False, False, False, True, True, True]
  attention_heads: 8
  attention_features: 64
  attention_multiplier: 2
  use_nearest_upsample: False
  use_skip_scale: True
  use_attention_bottleneck: True
  diffusion_sigma_distribution:
    _target_: audio_diffusion_pytorch.LogNormalDistribution
    mean: -3.0
    std: 1.0
  diffusion_sigma_data: 0.2
  diffusion_dynamic_threshold: 0.0

datamodule:
  _target_: main.module_base.Datamodule
  dataset:
    _target_: audio_data_pytorch.YoutubeDataset
    urls:
      - https://www.youtube.com/watch?v=ZaoNrHTfXDY # 1h GHØSTS
    root: ${data_dir}
    crop_length: 12 # seconds crops
    transforms:
      _target_: audio_data_pytorch.AllTransform
      source_rate: ${sampling_rate}
      target_rate: ${sampling_rate}
      random_crop_size: ${length}
      loudness: -20
  val_split: 0.01
  batch_size: 4
  num_workers: 8
  pin_memory: True

callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "valid_loss"   # name of the logged metric which determines when model is improving
    save_top_k: 1           # save k best models (determined by above metric)
    save_last: True         # additionaly always save model from last epoch
    mode: "min"             # can be "max" or "min"
    verbose: False
    dirpath: ${logs_dir}/ckpts/${now:%Y-%m-%d-%H-%M-%S}
    filename: '{epoch:02d}-{valid_loss:.3f}'

  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 2

  audio_samples_logger:
    _target_: main.module_base.SampleLogger
    num_items: 4
    channels: ${channels}
    sampling_rate: ${sampling_rate}
    length: ${length}
    sampling_steps: [3]
    diffusion_sampler:
      _target_: audio_diffusion_pytorch.ADPM2Sampler
      rho: 1.0
    diffusion_schedule:
      _target_: audio_diffusion_pytorch.KarrasSchedule
      sigma_min: 0.0001
      sigma_max: 3.0
      rho: 9.0

# loggers:
#   wandb:
#     _target_: pytorch_lightning.loggers.wandb.WandbLogger
#     project: ${oc.env:WANDB_PROJECT}
#     entity: ${oc.env:WANDB_ENTITY}
#     # offline: False  # set True to store all logs only locally
#     job_type: "train"
#     group: ""
#     save_dir: ${logs_dir}

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 0 # Set `1` to train on GPU, `0` to train on CPU only, and `-1` to train on all GPUs, default `0`
  precision: 32 # Precision used for tensors, default `32`
  accelerator: null # `ddp` GPUs train individually and sync gradients, default `None`
  min_epochs: 0
  max_epochs: 1
  enable_model_summary: False
  log_every_n_steps: 1 # Logs metrics every N batches
  check_val_every_n_epoch: null
  val_check_interval: ${log_every_n_steps}
```

It's the base_test.yaml but I've commented out the wandb logger and set the max_epochs in the trainer to 1

My env
```
DIR_LOGS=/logs
DIR_DATA=/data
HYDRA_FULL_ERROR=1
```
